---
title: "ML ROSE"
author: "Michael Harrison"
date: "May 4, 2017"
output: html_document
---
---
title: "ML Over-Undersample"
author: "Michael Harrison"
date: "May 4, 2017"
output: html_document
---

```{r}
library(ROSE)
```
- Training Dimensions
```{r}
dim(training)
```
- Training Class Percentages
```{r}
cbind(freq = table(training$CARAVAN), percentage = prop.table(table(training$CARAVAN))*100)
```


```{r}
#In case this file doesn't run upon R restart
#training$CARAVAN <- make.names(training$CARAVAN, unique = FALSE)
```

#Harness
```{r}
fitControl <- trainControl(method = "repeatedcv", number = 10, repeats = 3,
                           classProbs = TRUE, summaryFunction = twoClassSummary)
metric <- "ROC"
seed <- 10
```

```{r}
#establish over-undersampled training set
training_rose <- ROSE(CARAVAN~., data = training,
                      seed = seed)$data
table(training_rose$CARAVAN)
```

##GLMNET
```{r}
start.time <- Sys.time()
paraOn()
set.seed(seed)
roseGLMNET.trans <- train(CARAVAN~., data = training_rose, 
             method = "glmnet", metric = metric,
             preProc = c("BoxCox"),
             trControl = fitControl)
end.time <- Sys.time()
time.roseGLMNET.trans <- end.time - start.time
paraOff()
roseGLMNET.trans
```

##Random Forest
```{r}
start.time <- Sys.time()
paraOn()
set.seed(seed)
roseRF.trans <- train(CARAVAN~., data = training_rose,
                method = "rf", metric = metric,
                preProc = c("BoxCox"),
                trControl = fitControl)
end.time <- Sys.time()
time.roseRF.trans <- end.time - start.time
paraOff()
roseRF.trans
```


#Support Vector Machines
```{r}
#Support Vector Machines w/ Radial Basis Function
start.time <- Sys.time()
paraOn()
set.seed(seed)
roseSVM.trans <- train(CARAVAN~., data = training_rose, 
             method = "svmRadial", metric = metric,
             preProc = c("BoxCox"),
             trControl = fitControl)
end.time <- Sys.time()
time.roseSVM.trans <- end.time - start.time
paraOff()
roseSVM.trans
```


##K Nearest Neighbors
```{r}
start.time <- Sys.time()
paraOn()
set.seed(seed)
roseKNN.trans <- train(CARAVAN~., data = training_rose, 
             method = "knn", metric = metric,
             preProc = c("BoxCox"),
             trControl = fitControl)
end.time <- Sys.time()
time.roseKNN.trans <- end.time - start.time
paraOff()
roseKNN.trans
```


##Stochastic Gradient Boosting
```{r}
start.time <- Sys.time()
paraOn()
set.seed(seed)
roseGBM.trans <- train(CARAVAN~., data = training_rose,
                method = "gbm", metric = metric,
                preProc = c("BoxCox"),
                trControl = fitControl, verbose = FALSE)
end.time <- Sys.time()
time.roseGBM.trans <- end.time - start.time
paraOff()
roseGBM.trans
```
 
#Compare Results
```{r}
roseResults <- resamples(list(SVM = roseSVM.trans,
                              GLMNET = roseGLMNET.trans,
                              RF = roseRF.trans,
                              KNN = roseKNN.trans,
                              GBM = roseGBM.trans))
```

```{r}
scales <- list(x = list(relation = "free"),
               y = list(relation = "free"))
dotplot(roseResults, main = "ROSE Sampling Results", 
        scales = scales)
```

```{r}
summary(roseResults)
```

```{r}
roseResults$timings
```

```{r}
time.taken.rose <- list(roseSVM = time.roseSVM.trans,
                   roseGLMNET = time.roseGLMNET.trans,
                   roseRF = time.roseRF.trans,
                   roseKNN = time.roseKNN.trans,
                   roseGBM = time.roseGBM.trans)
time.taken.rose
```

#Predict on Validation Set
```{r}
pred_roseSVM <- predict(roseSVM.trans, newdata = validation)
pred_roseGLMNET <- predict(roseGLMNET.trans, newdata = validation)
pred_roseRF <- predict(roseRF.trans, newdata = validation)
pred_roseKNN <- predict(roseKNN.trans, newdata = validation)
pred_roseGBM <- predict(roseGBM.trans, newdata = validation)

AUC_roseSVM <- roc.curve(validation$CARAVAN, pred_roseSVM)
AUC_roseGLMNET <- roc.curve(validation$CARAVAN, pred_roseGLMNET)
AUC_roseRF <- roc.curve(validation$CARAVAN, pred_roseRF)
AUC_roseKNN <- roc.curve(validation$CARAVAN, pred_roseKNN)
AUC_roseGBM <- roc.curve(validation$CARAVAN, pred_roseGBM)
```

#AUC/ROC values to compare to other models
```{r}
AUC_roseResults <- list(roseSVM = AUC_roseSVM,
                        roseGLMNET = AUC_roseGLMNET,
                        roseRF = AUC_roseRF,
                        roseKNN = AUC_roseKNN,
                        roseGBM = AUC_roseGBM)
AUC_roseResults
```

