---
title: "ML Transformation Estimates - ROC"
author: "Michael Harrison"
date: "May 4, 2017"
output: html_document
---

#Load Libraries
```{r, warning=FALSE}
library(caret)
#For parallel processing
library(parallel)
library(doParallel)
```

# Training Initialization 
- Training Harness
```{r}
fitControl <- trainControl(method = "repeatedcv", number = 10, repeats = 3,
                           classProbs = TRUE, summaryFunction = twoClassSummary)
metric <- "ROC"
seed <- 10
training$CARAVAN <- make.names(training$CARAVAN, unique = FALSE)
```

#Configure parallel Processing
```{r}
#Configures parallel processing
paraOn <- function(){
        cluster <- makeCluster(detectCores()-1)
        registerDoParallel(cluster)}

paraOff <- function(){
        cluster <- makeCluster(detectCores()-1)
        stopCluster(cluster)
        registerDoSEQ()}

para <- function(state){
        cluster <- makeCluster(detectCores()-1)
        if(state == "on"){
                start.time <- Sys.time()
                registerDoParallel(cluster)
        }
        if(state == "off"){
                stopCluster(cluster)
                registerDoSEQ()
                end.time <- Sys.time()
                elapsed = end.time - start.time
                return(elapsed)
        }
        else{
                stop()
        }
}
```

#Baseline Algorithm Suite

##GLMNET
```{r}
start.time <- Sys.time()
paraOn()
set.seed(seed)
fitGLMNET.trans <- train(CARAVAN~., data = training, 
             method = "glmnet", metric = metric,
             preProc = c("BoxCox"),
             trControl = fitControl)
end.time <- Sys.time()
time.takenGLMNET.trans <- end.time - start.time
paraOff()
fitGLMNET.trans
```

##Random Forest
```{r}
start.time <- Sys.time()
paraOn()
set.seed(seed)
fitRF.trans <- train(CARAVAN~., data = training,
                method = "rf", metric = metric,
                preProc = c("BoxCox"),
                trControl = fitControl)
end.time <- Sys.time()
time.takenRF.trans <- end.time - start.time
paraOff()
fitRF.trans
```


#Support Vector Machines
```{r}
#Support Vector Machines w/ Radial Basis Function
start.time <- Sys.time()
paraOn()
set.seed(seed)
fitSVM.trans <- train(CARAVAN~., data = training, 
             method = "svmRadial", metric = metric,
             preProc = c("BoxCox"),
             trControl = fitControl)
end.time <- Sys.time()
time.takenSVM.trans <- end.time - start.time
paraOff()
fitSVM.trans
```


##K Nearest Neighbors
```{r}
start.time <- Sys.time()
paraOn()
set.seed(seed)
fitKNN.trans <- train(CARAVAN~., data = training, 
             method = "knn", metric = metric,
             preProc = c("BoxCox"),
             trControl = fitControl)
end.time <- Sys.time()
time.takenKNN.trans <- end.time - start.time
paraOff()
fitKNN.trans
```


##Stochastic Gradient Boosting
```{r}
start.time <- Sys.time()
paraOn()
set.seed(seed)
fitGBM.trans <- train(CARAVAN~., data = training,
                method = "gbm", metric = metric,
                preProc = c("BoxCox"),
                trControl = fitControl, verbose = FALSE)
end.time <- Sys.time()
time.takenBGM.trans <- end.time - start.time
paraOff()
fitGBM.trans
```
 
#Compare Results
```{r}
transformResults <- resamples(list(SVM = fitSVM.trans,
                                  GLMNET = fitGLMNET.trans,
                                  RF = fitRF.trans,
                                  KNN = fitKNN.trans,
                                  GBM = fitGBM.trans))
```

```{r}
scales <- list(x = list(relation = "free"),
               y = list(relation = "free"))
dotplot(transformResults, main = "Transformed Algorithm Suite Results", 
        scales = scales)
```

```{r}
summary(transformResults)
```

```{r}
transformResults$timings
```

