---
title: "ML Undersample and Train"
author: "Michael Harrison"
date: "May 4, 2017"
output: html_document
---

```{r}
library(ROSE)
```
- Training Dimensions
```{r}
dim(training)
```
- Training Class Percentages
```{r}
cbind(freq = table(training$CARAVAN), percentage = prop.table(table(training$CARAVAN))*100)
```


```{r}
#In case this file doesn't run upon R restart
#training$CARAVAN <- make.names(training$CARAVAN, unique = FALSE)
```

#Harness
```{r}
fitControl <- trainControl(method = "repeatedcv", number = 10, repeats = 3,
                           classProbs = TRUE, summaryFunction = twoClassSummary)
metric <- "ROC"
seed <- 10
```

```{r}
#establish undersampled training set
training_under <- ovun.sample(CARAVAN~., data = training,
                              method = "under", N = 488, seed = seed)$data
table(training_under$CARAVAN)
```

##GLMNET
```{r}
start.time <- Sys.time()
paraOn()
set.seed(seed)
underGLMNET.trans <- train(CARAVAN~., data = training_under, 
             method = "glmnet", metric = metric,
             preProc = c("BoxCox"),
             trControl = fitControl)
end.time <- Sys.time()
time.underGLMNET.trans <- end.time - start.time
paraOff()
underGLMNET.trans
```

##Random Forest
```{r}
start.time <- Sys.time()
paraOn()
set.seed(seed)
underRF.trans <- train(CARAVAN~., data = training_under,
                method = "rf", metric = metric,
                preProc = c("BoxCox"),
                trControl = fitControl)
end.time <- Sys.time()
time.underRF.trans <- end.time - start.time
paraOff()
underRF.trans
```


#Support Vector Machines
```{r}
#Support Vector Machines w/ Radial Basis Function
start.time <- Sys.time()
paraOn()
set.seed(seed)
underSVM.trans <- train(CARAVAN~., data = training_under, 
             method = "svmRadial", metric = metric,
             preProc = c("BoxCox"),
             trControl = fitControl)
end.time <- Sys.time()
time.underSVM.trans <- end.time - start.time
paraOff()
underSVM.trans
```


##K Nearest Neighbors
```{r}
start.time <- Sys.time()
paraOn()
set.seed(seed)
underKNN.trans <- train(CARAVAN~., data = training_under, 
             method = "knn", metric = metric,
             preProc = c("BoxCox"),
             trControl = fitControl)
end.time <- Sys.time()
time.underKNN.trans <- end.time - start.time
paraOff()
underKNN.trans
```


##Stochastic Gradient Boosting
```{r}
start.time <- Sys.time()
paraOn()
set.seed(seed)
underGBM.trans <- train(CARAVAN~., data = training_under,
                method = "gbm", metric = metric,
                preProc = c("BoxCox"),
                trControl = fitControl, verbose = FALSE)
end.time <- Sys.time()
time.underGBM.trans <- end.time - start.time
paraOff()
underGBM.trans
```
 
#Compare Results
```{r}
underResults <- resamples(list(underSVM = underSVM.trans,
                               underGLMNET = underGLMNET.trans,
                               underRF = underRF.trans,
                               underKNN = underKNN.trans,
                               underGBM = underGBM.trans))
```

```{r}
scales <- list(x = list(relation = "free"),
               y = list(relation = "free"))
dotplot(underResults, main = "Undersampling Results", 
        scales = scales)
```

```{r}
summary(underResults)
```

```{r}
underResults$timings
```

```{r}
time.taken.under <- list(underSVM = time.underSVM.trans,
                   underGLMNET = time.underGLMNET.trans,
                   underRF = time.underRF.trans,
                   underKNN = time.underKNN.trans,
                   underGBM = time.underGBM.trans)
time.taken.under
```

#Predict on Validation Set
```{r}
pred_underSVM <- predict(underSVM.trans, newdata = validation)
pred_underGLMNET <- predict(underGLMNET.trans, newdata = validation)
pred_underRF <- predict(underRF.trans, newdata = validation)
pred_underKNN <- predict(underKNN.trans, newdata = validation)
pred_underGBM <- predict(underGBM.trans, newdata = validation)

AUC_underSVM <- roc.curve(validation$CARAVAN, pred_underSVM)
AUC_underGLMNET <- roc.curve(validation$CARAVAN, pred_underGLMNET)
AUC_underRF <- roc.curve(validation$CARAVAN, pred_underRF)
AUC_underKNN <- roc.curve(validation$CARAVAN, pred_underKNN)
AUC_underGBM <- roc.curve(validation$CARAVAN, pred_underGBM)
```

#AUC/ROC values to compare to other models
```{r}
AUC_underResults <- list(underSVM = AUC_underSVM,
                    underGLMNET = AUC_underGLMNET,
                    underRF = AUC_underRF,
                    underKNN = AUC_underKNN,
                    underGBM = AUC_underGBM)
AUC_underResults
```

